name: Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-releases:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build.sh
        run: |
          chmod +x build.sh
          sudo ./build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-macos11
          path: |
            *-macos11.tar.gz

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*-macos11.tar.gz
          file_glob: true
          overwrite: false
          tag: release-macos11
